project:
  type: website

website:
  title: "Samar Zayan"
  favicon: favicon.png
  search:
    location: navbar
    type: overlay
  navbar:
    right:
      - text: "Home"
        file: index.qmd
      - text: "Blog"
        file: blog.qmd
      - text: "fast.ai"
        file: fast.ai.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "About"
        file: about.qmd
  sidebar:
    - title: "fast.ai"
      style: "docked"
      contents: 
        - fast.ai.qmd
        - section: "Practical Deep Learning For Coders"
          contents:
            - section: "Lesson Notes"
              contents:
                - lesson0.qmd
                - lesson_01.ipynb
            - text: "---"
            - section: "Text Book Notes"
              contents:
                - chapter1.qmd
            - text: "---"
            - section: "Code Experiments"
              contents: 
                - safedriving.qmd
        - section: "Live Coding"
          contents:
            - live_coding_1.qmd
            - live_coding_2.qmd
        - text: "---"
    - title: "Resources"
      style: "docked"
      contents:
        - resources.qmd 
        - technical_glossary.qmd
  page-navigation: true
  reader-mode: true
format:
  html:
    mainfont: "Ebrima"
    theme: theme.scss
    css: styles.css
    toc: true
